### ISSUE TITLE
kibana 외부 접속 불가 문제

### ISSUE THREAD

**Issue by ksh3490** [ksh3490/my-elk#2]

**Comment by ksh3490** [comment]
현재 웹 브라우저를 통해 Kibana 접속 시 Kibana Pod 로그에서 발견되는 에러 메시지
- [index_not_found_exception]: no such index [.kibana]
- ResponseError: index_not_found_exception
- [version_conflict_engine_exception]: [config:7.10.2]: version conflict, document already exists (current version [1])
- [illegal_argument_exception]: request [/_license] contains unrecognized parameter: [accept_enterprise]
- TypeError: Cannot read property 'hits' of undefined\n    at UsageCollector.fetch (/usr/share/kibana/src/plugins/data/server/search/collectors/fetch.js:44:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ksh3490** [comment]
kibana와 elasticsearch가 정상적으로 연동되지 않아 오류가 발생하는 듯함

kibana.yaml에서 elasticsearch.hosts 값을 "http://elasticsearch-svc:9200" -> "http://192.168.49.2:30920"로 바꿔서 테스트:
  - curl -XGET http://192.168.49.2:30920/_cat/indices/ 명령어를 반복 실행 시
    gree open .kibana_2 ...
    gree open .kibana_1 ...
    gree open .tasks ...
    등이 표시되다가 사라지고 다시 생기는 현상 발견

**Comment by ksh3490** [comment]
지금까지 Windows WSL 2와 minikube에서 테스트를 했으나, 이럴 경우 minikube 상에서 새로 배포하는 Service의 포트가 제대로 바인딩 되지 않는 문제가 있다고 함... (참고: https://github.com/alicek106/start-docker-kubernetes/issues/2)

다른 테스트 환경을 찾아봐야 할 듯함

**Comment by ksh3490** [comment]
Docker desktop for Windows + WSL2 Backend에서 Kubernetes 활성화하는 환경으로 테스트 중

현재 wsl에서 kubectl get nodes 실행 시 'no server found for cluster "minikube"' 에러 발생하여 해결 중

**Comment by ksh3490** [comment]
'no server found for cluster "minikube"' 오류 해결
  오류 발생 원안:
    - 기존에 wsl상에서 사용 중이던 kubectl 명령어가 실제로는 .bashrc 파일에 alias kubectl="minikube kubectl --"로 등록되어 있었음. 
    - 즉, 지금은 사용하지 않는 minikube를 통해 kubectl 명령어를 실행하고 있던 것
 
  해결 과정:
  - .bashrc 파일의 alias kubectl="minikube kubectl --" 부분 삭제 후 source ~/.bachrc 명령어 실행으로 변경사항 적용 및 wsl 재부팅
